<?php $_element = $this->getElement() ?>
<?php $this->checkFieldDisable() ?>
<tr>
    <td class="value">
        <?php echo trim($this->getElementHtml()) ?>
        <?php if ($_element->getNote()) : ?>
            <p class="note"><?php echo $_element->getNote() ?></p>
        <?php endif; ?>
    </td>
    <td class="scope-label"><span class="nobr"><?php echo $this->getScopeLabel() ?></span></td>
    <?php if ($this->canDisplayUseDefault()): ?>
    <td class="value use-default">
        <input <?php if($_element->getReadonly()):?> disabled="disabled"<?php endif; ?> type="checkbox" name="use_default[]" id="<?php echo $_element->getHtmlId() ?>_default"<?php if ($this->usedDefault()): ?> checked="checked"<?php endif; ?> onclick="toggleValueElements(this, this.parentNode.parentNode)" value="<?php echo $this->getAttributeCode() ?>"/>
        <label for="<?php echo $_element->getHtmlId() ?>_default" class="normal"><?php echo $this->__('Use Default Value') ?></label>
    </td>
    <?php endif; ?>
</tr>